### ISSUE TITLE
Change code to be like python 3.11.0a5 

### ISSUE THREAD

**Issue by DanieleIsoni** [clbarnes/backports.strenum#3]
Maybe the following line should be removed so that it's the same as the code from [python 3.11.0a5](https://github.com/python/cpython/blob/0ac5372bf6b937ed44a8f9c4e402d024fcd80870/Lib/enum.py#L1269)

https://github.com/clbarnes/backports.strenum/blob/f7e4e5c1e381467e62d0776b9b2b5319879448e9/backports/strenum/strenum.py#L33

**Comment by clbarnes** [comment]
Yes, this generally needs updating in line with whatever's going on in mainline, as it wasn't released as planned in 3.10. I may hold off until 3.11 has matured a bit more, though, otherwise it's an endless game of catch-up. Thanks for noting one such change!

**Comment by tmke8** [comment]
I think that line is still needed, because, in Python 3.11, there is the new `ReprEnum` class which is special-cased to not have an overwritten `__str__` method. However, we can't recreate that effect without changing the internals of `Enum`, so it's necessary to manually restore the original `__str__`.

**Comment by clbarnes** [comment]
I'm pretty sure we're up to date as it stands.
